name: number_memory_game
description: 番号記憶ゲームアプリ
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
